default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: hello_rails_back_end_development

test:
  <<: *default
  database: hello_rails_back_end_test

production:
  <<: *default
  database: hello_rails_back_end_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
